### ISSUE TITLE
Docs: Feedback for Deploying a Cluster on Google Cloud Platform

### ISSUE THREAD

**Issue by Vedimudi** [hazelcast/hz-docs#444]
Hi, I have some feedback about [this page](https://github.com/hazelcast/hz-docs/edit/main/docs/modules/deploy/pages/deploying-on-gcp.adoc)
WARNING: Couldn't connect to the service, [1] retrying in 1 seconds...
May 05, 2022 7:44:59 PM com.hazelcast.spi.utils.RetryUtils
WARNING: Couldn't connect to the service, [2] retrying in 2 seconds...
May 05, 2022 7:45:01 PM com.hazelcast.spi.utils.RetryUtils
WARNING: Couldn't connect to the service, [3] retrying in 3 seconds...
May 05, 2022 7:45:04 PM com.hazelcast.instance.impl.Node
SEVERE: [172.17.0.4]:5702 [hello-world] [5.1.1] Node creation failed
java.lang.RuntimeException: Failed to configure discovery strategies
        at com.hazelcast.spi.discovery.impl.DefaultDiscoveryService.loadDiscoveryStrategies(DefaultDiscoveryService.java:161)
        at com.hazelcast.spi.discovery.impl.DefaultDiscoveryService.<init>(DefaultDiscoveryService.java:58)
        at com.hazelcast.spi.discovery.impl.DefaultDiscoveryServiceProvider.newDiscoveryService(DefaultDiscoveryServiceProvider.java:29)
        at com.hazelcast.instance.impl.Node.createDiscoveryService(Node.java:342)
        at com.hazelcast.instance.impl.Node.<init>(Node.java:266)
        at com.hazelcast.instance.impl.HazelcastInstanceImpl.createNode(HazelcastInstanceImpl.java:149)
        at com.hazelcast.instance.impl.HazelcastInstanceImpl.<init>(HazelcastInstanceImpl.java:118)
        at com.hazelcast.instance.impl.HazelcastInstanceFactory.constructHazelcastInstance(HazelcastInstanceFactory.java:217)
        at com.hazelcast.instance.impl.HazelcastInstanceFactory.newHazelcastInstance(HazelcastInstanceFactory.java:196)
        at com.hazelcast.instance.impl.HazelcastInstanceFactory.newHazelcastInstance(HazelcastInstanceFactory.java:134)
        at com.hazelcast.core.Hazelcast.newHazelcastInstance(Hazelcast.java:61)

**Comment by Serdaro** [comment]
@Vedimudi , are you still experiencing the above issue?

**Comment by Serdaro** [comment]
Closing due to inactivity.
